services:
  backend:
    build:
      context: .
      dockerfile: docker/django/Dockerfile.prod
    image: ghcr.io/tupilingo/backend:latest
    restart: always
    env_file:
      - .env
    environment:
      - PRODUCTION=True
      - DEBUG=False
    # Em produção usaríamos labels para Traefik ou porta direta dependendo da infra
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    profiles: [] # Sempre ativo por padrão no compose.prod.yml

  celery_worker:
    build:
      context: .
      dockerfile: docker/django/Dockerfile.prod
    image: ghcr.io/tupilingo/backend:latest
    restart: always
    command: ["celery", "-A", "config", "worker", "-l", "INFO"]
    env_file:
      - .env
    environment:
      - PRODUCTION=True
      - DEBUG=False
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    profiles: []
