# Generated by Django 6.1 on 2026-09-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tupi_name', models.CharField(max_length=200)),
                ('spring_x', models.FloatField(default=4000.0)),
                ('spring_y', models.FloatField(default=4500.0)),
                ('estuary_x', models.FloatField(default=6000.0)),
                ('estuary_y', models.FloatField(default=5500.0)),
                ('control_points', models.JSONField(default=list, help_text='Array de segmentos Bézier cúbicos com largura dinâmica')),
                ('max_width', models.FloatField(default=35.0)),
                ('flow_speed', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tupi_name', models.CharField(max_length=200)),
                ('historical_period', models.CharField(default='Século XVI', max_length=100)),
                ('primary_dialect', models.CharField(default='Tupi Clássico', max_length=100)),
                ('biome', models.CharField(default='mataAtlantica', max_length=50)),
                ('completion_xp', models.IntegerField(default=350)),
                ('center_x', models.FloatField(default=5000.0)),
                ('center_y', models.FloatField(default=5000.0)),
                ('polygon_points', models.JSONField(default=list, help_text='Lista de [x, y] definindo a fronteira geográfica')),
                ('is_unlocked', models.BooleanField(default=True)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEpoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('active_territory_slugs', models.JSONField(default=list)),
                ('active_alliance_slugs', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('waypoints', models.JSONField(default=list, help_text='Lista ordenada de coordenadas [x, y]')),
                ('is_discovered', models.BooleanField(default=True)),
                ('color_hex', models.CharField(default='#E5A93C', max_length=10)),
                ('stroke_width', models.FloatField(default=2.5)),
                ('historical_period', models.CharField(default='Pré-1500', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorldMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pindorama Histórico', max_length=150)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('preview', 'Homologação'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('width', models.FloatField(default=10000.0)),
                ('height', models.FloatField(default=10000.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('overlay_type', models.CharField(default='alliance', max_length=50)),
                ('polygon_points', models.JSONField(default=list)),
                ('base_color_hex', models.CharField(default='#E53935', max_length=10)),
                ('epoch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='world_builder.timelineepoch')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tupi_name', models.CharField(max_length=200)),
                ('x', models.FloatField(default=5000.0)),
                ('y', models.FloatField(default=5000.0)),
                ('evolution_stage', models.IntegerField(default=2, help_text='0: Oculta, 1: Descoberta, 2: Explorada, 3: Dominada, 4/5: Histórica/Viva')),
                ('resident_count', models.IntegerField(default=250)),
                ('dialect_variant', models.CharField(default='Tupi Antigo', max_length=100)),
                ('leader_name', models.CharField(default='Cacique Ancestral', max_length=150)),
                ('historical_context', models.TextField(blank=True)),
                ('has_boss_challenge', models.BooleanField(default=False)),
                ('is_unlocked', models.BooleanField(default=True)),
                ('active_epochs', models.JSONField(default=list, help_text='Lista de IDs das épocas históricas visíveis')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='world_builder.territory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_main', models.BooleanField(default=True)),
                ('target_x', models.FloatField(default=5000.0)),
                ('target_y', models.FloatField(default=5000.0)),
                ('reward_xp', models.IntegerField(default=150)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='world_builder.village')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('indigenous_nation', models.CharField(max_length=100)),
                ('epoch', models.CharField(default='1554', max_length=50)),
                ('lore', models.TextField()),
                ('dialogue_greeting', models.CharField(default='Kauê!', max_length=255)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npcs', to='world_builder.village')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('artifact_name', models.CharField(max_length=200)),
                ('tupi_lore', models.TextField()),
                ('xp_bonus', models.IntegerField(default=100)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='world_builder.village')),
            ],
        ),
        migrations.AddField(
            model_name='territory',
            name='world_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='world_builder.worldmap'),
        ),
        migrations.CreateModel(
            name='WorldVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_tag', models.CharField(max_length=50)),
                ('commit_message', models.TextField(default='Atualização do mundo')),
                ('author_role', models.CharField(default='Content Editor', max_length=100)),
                ('snapshot_data', models.JSONField(help_text='JSON completo contendo todas as entidades da versão')),
                ('diff_hash', models.CharField(blank=True, max_length=64)),
                ('is_rollback_target', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='world_builder.worldmap')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
