# Generated by Django 6.1 on 2026-08-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_audit_v3_uuid_email_choices_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('calculated_level', models.IntegerField()),
                ('calculated_theta', models.FloatField(default=0.0)),
                ('is_suspected_cheating', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hash', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('selected_letter', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.FloatField()),
                ('param_a', models.FloatField(default=1.2)),
                ('param_b', models.FloatField(default=0.0)),
                ('param_c', models.FloatField(default=0.25)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='nivelamento.testattempt')),
            ],
        ),
    ]
