# Generated by Django 6.1 on 2026-08-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivelamento', '0001_initial'),
        ('trilha', '0001_initial'),
        ('users', '0002_audit_v3_uuid_email_choices_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeritem',
            options={'verbose_name': 'Resposta de Questão', 'verbose_name_plural': 'Respostas de Questões'},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'verbose_name': 'Tentativa de Nivelamento', 'verbose_name_plural': 'Tentativas de Nivelamento'},
        ),
        migrations.AddField(
            model_name='testattempt',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Variante (língua) para a qual este teste foi realizado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='trilha.variantetupi', verbose_name='Variante Tupi'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='is_correct',
            field=models.BooleanField(verbose_name='Está Correta'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='param_a',
            field=models.FloatField(default=1.2, verbose_name='Parâmetro A (Discriminação)'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='param_b',
            field=models.FloatField(default=0.0, verbose_name='Parâmetro B (Dificuldade)'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='param_c',
            field=models.FloatField(default=0.25, verbose_name='Parâmetro C (Chute)'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='question_hash',
            field=models.CharField(help_text='Identificador da questão gerada (primeiros 250 chars do hash).', max_length=255, verbose_name='Hash da Questão'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='question_text',
            field=models.TextField(verbose_name='Texto da Questão'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='selected_letter',
            field=models.CharField(max_length=1, verbose_name='Letra Selecionada'),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='time_taken_seconds',
            field=models.FloatField(verbose_name='Tempo de Resposta (s)'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='calculated_level',
            field=models.IntegerField(verbose_name='Nível Calculado (1-10)'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='calculated_theta',
            field=models.FloatField(default=0.0, help_text='Parâmetro de habilidade estimado pelo algoritmo TRI.', verbose_name='Theta TRI'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='is_suspected_cheating',
            field=models.BooleanField(default=False, help_text='Flagado quando o algoritmo detecta padrão de respostas aleatórias.', verbose_name='Suspeita de Chute'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('user', 'variante')},
        ),
        migrations.CreateModel(
            name='UserVarianteLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nível (1-10)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis_por_variante', to='users.userprofile')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis_usuarios', to='trilha.variantetupi')),
            ],
            options={
                'verbose_name': 'Nível do Usuário por Variante',
                'verbose_name_plural': 'Níveis dos Usuários por Variante',
                'unique_together': {('user', 'variante')},
            },
        ),
    ]
