# Generated by Django 6.1 on 2026-09-14 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('window_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_sessions_count', models.PositiveIntegerField(default=0)),
                ('avg_fps', models.FloatField(default=60.0)),
                ('avg_frame_time_ms', models.FloatField(default=16.6)),
                ('raster_thread_time_ms', models.FloatField(default=5.2)),
                ('ui_thread_time_ms', models.FloatField(default=6.1)),
                ('p95_latency_ms', models.FloatField(default=120.0)),
                ('cache_hit_rate', models.FloatField(default=0.92)),
                ('active_biomes_count', models.PositiveIntegerField(default=1)),
                ('quests_completed_hourly', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica Agregada',
                'verbose_name_plural': 'Métricas Agregadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('actor_role', models.CharField(default='Administrator', max_length=100)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CrashCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('error_type', models.CharField(max_length=150)),
                ('exception_message', models.TextField()),
                ('impacted_users_approx', models.PositiveIntegerField(default=1)),
                ('occurrences_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('stacktrace_summary', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cluster de Falha',
                'verbose_name_plural': 'Clusters de Falhas',
                'ordering': ['-occurrences_count', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.PositiveIntegerField(default=100)),
                ('target_device_classes', models.JSONField(blank=True, default=list)),
                ('target_app_versions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_class', models.CharField(default='mid', max_length=50)),
                ('avg_fps', models.FloatField(default=60.0)),
                ('frame_drops_pct', models.FloatField(default=0.5)),
                ('memory_mb', models.FloatField(default=180.0)),
                ('gpu_tier', models.CharField(default='impeller-vulkan', max_length=100)),
                ('sample_count', models.PositiveIntegerField(default=1)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot de Desempenho',
                'verbose_name_plural': 'Snapshots de Desempenho',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('OUTAGE', 'Outage')], default='HEALTHY', max_length=20)),
                ('latency_ms', models.FloatField(default=15.0)),
                ('cpu_pct', models.FloatField(default=12.0)),
                ('memory_pct', models.FloatField(default=35.0)),
                ('uptime_pct', models.FloatField(default=99.98)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saúde de Serviço',
                'verbose_name_plural': 'Saúde de Serviços',
                'ordering': ['service_name'],
            },
        ),
    ]
