# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tupilingo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tupilingo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftupilingo.proto\x12\ttupilingo\"\xe8\x01\n\x12UserProfileMessage\x12\x14\n\x0csupabase_uid\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08xp_total\x18\x04 \x01(\x05\x12\x13\n\x0bstreak_dias\x18\x05 \x01(\x05\x12\x13\n\x0bnivel_atual\x18\x06 \x01(\x05\x12\x0f\n\x07\x63onchas\x18\x07 \x01(\x05\x12\x1d\n\x15variante_ativa_codigo\x18\x08 \x01(\t\x12\x1b\n\x13variante_ativa_nome\x18\t \x01(\t\x12\x16\n\x0eofensiva_ativa\x18\n \x01(\x08\"\xb0\x01\n\x19UserLessonProgressMessage\x12\x10\n\x08licao_id\x18\x01 \x01(\x05\x12\x0e\n\x06numero\x18\x02 \x01(\x05\x12\x0e\n\x06titulo\x18\x03 \x01(\t\x12\x11\n\tconcluida\x18\x04 \x01(\x08\x12\x18\n\x10pontuacao_maxima\x18\x05 \x01(\x05\x12\x12\n\ntentativas\x18\x06 \x01(\x05\x12 \n\x18\x64\x61ta_conclusao_timestamp\x18\x07 \x01(\x03\"\xb9\x01\n\x0fQuizItemMessage\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x12\n\ntermo_tupi\x18\x02 \x01(\t\x12\x18\n\x10traducao_correta\x18\x03 \x01(\t\x12\x13\n\x0b\x64istratores\x18\x04 \x03(\t\x12\x16\n\x0eregra_contexto\x18\x05 \x01(\t\x12\x11\n\tenunciado\x18\x06 \x01(\t\x12\x12\n\nexplicacao\x18\x07 \x01(\t\x12\x13\n\x0b\x63uriosidade\x18\x08 \x01(\t\"\xa4\x01\n\x10QuizBlockMessage\x12\x0f\n\x07quiz_id\x18\x01 \x01(\t\x12\x17\n\x0fvariante_codigo\x18\x02 \x01(\t\x12\r\n\x05nivel\x18\x03 \x01(\x05\x12\x0c\n\x04tema\x18\x04 \x01(\t\x12,\n\x08questoes\x18\x05 \x03(\x0b\x32\x1a.tupilingo.QuizItemMessage\x12\x1b\n\x13gerado_em_timestamp\x18\x06 \x01(\x03\x42&\n\x13\x63om.tupilingo.protoZ\x0ftupilingo/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tupilingo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.tupilingo.protoZ\017tupilingo/proto'
  _globals['_USERPROFILEMESSAGE']._serialized_start=31
  _globals['_USERPROFILEMESSAGE']._serialized_end=263
  _globals['_USERLESSONPROGRESSMESSAGE']._serialized_start=266
  _globals['_USERLESSONPROGRESSMESSAGE']._serialized_end=442
  _globals['_QUIZITEMMESSAGE']._serialized_start=445
  _globals['_QUIZITEMMESSAGE']._serialized_end=630
  _globals['_QUIZBLOCKMESSAGE']._serialized_start=633
  _globals['_QUIZBLOCKMESSAGE']._serialized_end=797
# @@protoc_insertion_point(module_scope)
