# Generated by Django 6.1 on 2026-08-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Narrativa')),
                ('numero', models.PositiveSmallIntegerField(help_text='Ordem sequencial dentro da trilha.', verbose_name='Número do Capítulo')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['trilha', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cenário')),
                ('background_image', models.ImageField(blank=True, help_text='Imagem de fundo do mapa interativo para este capítulo.', null=True, upload_to='scenarios/backgrounds/', verbose_name='Imagem de Fundo')),
                ('ambient_audio', models.FileField(blank=True, help_text='Sons de fundo como floresta, rio, pássaros...', null=True, upload_to='scenarios/audio/', verbose_name='Áudio Ambiente')),
                ('palette', models.JSONField(blank=True, default=dict, help_text='JSON com cores do tema. Ex: {"primary": "#0E5D4E", "secondary": "#D08A45"}', verbose_name='Paleta de Cores')),
            ],
            options={
                'verbose_name': 'Cenário',
                'verbose_name_plural': 'Cenários',
            },
        ),
        migrations.CreateModel(
            name='TrilhaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo / Slogan')),
                ('publicada', models.BooleanField(default=False, help_text='Somente trilhas publicadas aparecem no app.', verbose_name='Publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trilha Histórica',
                'verbose_name_plural': 'Trilhas Históricas',
            },
        ),
        migrations.CreateModel(
            name='VarianteTupi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Tupi Antigo, Nheengatu, Guarani Mbya', max_length=100, unique=True, verbose_name='Nome da Variante')),
                ('codigo', models.SlugField(help_text='Ex: tupi_antigo, nheengatu. Usado internamente e no RAG.', unique=True, verbose_name='Código Único')),
                ('descricao', models.TextField(blank=True, help_text='Contexto histórico e cultural desta variante.', verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, default='🌿', help_text='Emoji representativo, ex: 🌿 ou 🏹', max_length=10, verbose_name='Ícone Emoji')),
                ('ativo', models.BooleanField(default=True, help_text='Desativar oculta a variante do app sem excluí-la.', verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem que aparece na tela de seleção.', verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Variante Tupi',
                'verbose_name_plural': 'Variantes Tupi',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Licao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Lição')),
                ('descricao', models.CharField(blank=True, help_text='Aparece no pop-up do mapa antes de começar.', max_length=300, verbose_name='Descrição curta')),
                ('numero', models.PositiveSmallIntegerField(help_text='Ordem dentro do capítulo.', verbose_name='Número da Lição')),
                ('xp_base', models.PositiveSmallIntegerField(default=20, help_text='XP concedido ao concluir esta lição sem erros.', verbose_name='XP Base')),
                ('pos_x', models.FloatField(default=50.0, help_text='Posição horizontal (0=esquerda, 100=direita) no cenário.', verbose_name='Posição X no mapa (%)')),
                ('pos_y', models.FloatField(default=50.0, help_text='Posição vertical (0=topo, 100=fundo) no cenário.', verbose_name='Posição Y no mapa (%)')),
                ('publicada', models.BooleanField(default=False, verbose_name='Publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licoes', to='trilha.capitulo', verbose_name='Capítulo')),
            ],
            options={
                'verbose_name': 'Lição',
                'verbose_name_plural': 'Lições',
                'ordering': ['capitulo', 'numero'],
                'unique_together': {('capitulo', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='capitulo',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitulos', to='trilha.scenario', verbose_name='Cenário'),
        ),
        migrations.CreateModel(
            name='StoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('story', 'Narrativa'), ('curiosity', 'Curiosidade Cultural'), ('dialogue', 'Diálogo'), ('image', 'Imagem'), ('audio', 'Áudio'), ('vocabulary', 'Vocabulário')], max_length=20, verbose_name='Tipo de Bloco')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título do Bloco')),
                ('conteudo', models.TextField(blank=True, help_text='Texto principal da narrativa, curiosidade ou diálogo.', verbose_name='Conteúdo de Texto')),
                ('midia', models.FileField(blank=True, help_text='Imagem ou áudio anexado a este bloco.', null=True, upload_to='storyblocks/media/', verbose_name='Mídia')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='JSON com dados complementares. Ex: {"personagem": "Pajé", "lado": "esquerda"}', verbose_name='Dados Extras')),
                ('xp_bonus', models.PositiveSmallIntegerField(default=0, help_text='XP adicional concedido ao usuário por explorar este bloco.', verbose_name='XP Bônus')),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_blocks', to='trilha.licao', verbose_name='Lição')),
            ],
            options={
                'verbose_name': 'Bloco de História',
                'verbose_name_plural': 'Blocos de História',
                'ordering': ['licao', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ExercicioEscolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500, verbose_name='Enunciado')),
                ('explicacao', models.TextField(blank=True, help_text='Exibida após o usuário responder. Explica a resposta correta com contexto cultural.', verbose_name='Explicação')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='Dificuldade')),
                ('pontos_base', models.PositiveSmallIntegerField(default=10, verbose_name='Pontos Base (XP)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem na Lição')),
                ('midia', models.FileField(blank=True, help_text='Imagem ou áudio de apoio ao enunciado.', null=True, upload_to='exercicios/media/', verbose_name='Mídia de Apoio')),
                ('opcoes', models.JSONField(help_text='Lista de strings. Ex: ["Karai", "Tupã", "Mbya", "Jaguara"]', verbose_name='Opções')),
                ('resposta_correta', models.PositiveSmallIntegerField(help_text='Índice 0-based da opção correta. Ex: 1 → segunda opção.', verbose_name='Índice da Resposta Correta')),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='trilha.licao', verbose_name='Lição')),
                ('story_block', models.ForeignKey(blank=True, help_text='Se preenchido, este exercício aparece dentro daquele bloco específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='trilha.storyblock', verbose_name='Bloco de História')),
            ],
            options={
                'verbose_name': 'Exercício de Múltipla Escolha',
                'verbose_name_plural': 'Exercícios de Múltipla Escolha',
            },
        ),
        migrations.CreateModel(
            name='ExercicioCompletar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500, verbose_name='Enunciado')),
                ('explicacao', models.TextField(blank=True, help_text='Exibida após o usuário responder. Explica a resposta correta com contexto cultural.', verbose_name='Explicação')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='Dificuldade')),
                ('pontos_base', models.PositiveSmallIntegerField(default=10, verbose_name='Pontos Base (XP)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem na Lição')),
                ('midia', models.FileField(blank=True, help_text='Imagem ou áudio de apoio ao enunciado.', null=True, upload_to='exercicios/media/', verbose_name='Mídia de Apoio')),
                ('texto_com_lacunas', models.TextField(help_text="Use ___ para marcar cada lacuna. Ex: 'Tupã é o ___ do trovão.'", verbose_name='Texto com Lacunas')),
                ('respostas_corretas', models.JSONField(help_text='Lista de strings. Ex: ["deus"] para a lacuna acima.', verbose_name='Respostas Corretas')),
                ('tolerancia_levenshtein', models.PositiveSmallIntegerField(default=2, help_text='Distância máxima permitida. 0=exato, 1=1 erro, 2=2 erros.', verbose_name='Tolerância a Erros (Levenshtein)')),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='trilha.licao', verbose_name='Lição')),
                ('story_block', models.ForeignKey(blank=True, help_text='Se preenchido, este exercício aparece dentro daquele bloco específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='trilha.storyblock', verbose_name='Bloco de História')),
            ],
            options={
                'verbose_name': 'Exercício de Completar',
                'verbose_name_plural': 'Exercícios de Completar',
            },
        ),
        migrations.CreateModel(
            name='ExercicioAssociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500, verbose_name='Enunciado')),
                ('explicacao', models.TextField(blank=True, help_text='Exibida após o usuário responder. Explica a resposta correta com contexto cultural.', verbose_name='Explicação')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='Dificuldade')),
                ('pontos_base', models.PositiveSmallIntegerField(default=10, verbose_name='Pontos Base (XP)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem na Lição')),
                ('midia', models.FileField(blank=True, help_text='Imagem ou áudio de apoio ao enunciado.', null=True, upload_to='exercicios/media/', verbose_name='Mídia de Apoio')),
                ('coluna_esquerda', models.JSONField(help_text='Lista de strings. Ex: ["Tupã", "Mboi"]', verbose_name='Coluna da Esquerda')),
                ('coluna_direita', models.JSONField(help_text='Lista de strings. Ex: ["Deus do trovão", "Serpente"]', verbose_name='Coluna da Direita')),
                ('associacao_correta', models.JSONField(help_text='Dict índice→índice. Ex: {"0": "0", "1": "1"}', verbose_name='Associação Correta')),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='trilha.licao', verbose_name='Lição')),
                ('story_block', models.ForeignKey(blank=True, help_text='Se preenchido, este exercício aparece dentro daquele bloco específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='trilha.storyblock', verbose_name='Bloco de História')),
            ],
            options={
                'verbose_name': 'Exercício de Associação',
                'verbose_name_plural': 'Exercícios de Associação',
            },
        ),
        migrations.AddField(
            model_name='capitulo',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='trilha.trilhahistorica', verbose_name='Trilha'),
        ),
        migrations.AddField(
            model_name='trilhahistorica',
            name='variante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trilha', to='trilha.variantetupi', verbose_name='Variante'),
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_tupi', models.CharField(max_length=200, verbose_name='Palavra em Tupi')),
                ('traducao_pt', models.CharField(max_length=200, verbose_name='Tradução em Português')),
                ('transliteracao', models.CharField(blank=True, help_text="Como pronunciar. Ex: 'tsu-PÃ'", max_length=200, verbose_name='Transliteração Fonética')),
                ('audio', models.FileField(blank=True, null=True, upload_to='vocabulary/audio/', verbose_name='Áudio de Pronúncia')),
                ('exemplo_tupi', models.CharField(blank=True, max_length=400, verbose_name='Frase de Exemplo (Tupi)')),
                ('exemplo_pt', models.CharField(blank=True, max_length=400, verbose_name='Frase de Exemplo (Português)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='trilha.licao', verbose_name='Lição')),
            ],
            options={
                'verbose_name': 'Item de Vocabulário',
                'verbose_name_plural': 'Itens de Vocabulário',
                'ordering': ['licao', 'ordem'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='capitulo',
            unique_together={('trilha', 'numero')},
        ),
    ]
