# Generated by Django 6.1 on 2026-08-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='categoria',
            field=models.CharField(default='geral', help_text='Ex: fauna, flora, natureza, mitologia, corpo, geral.', max_length=100, verbose_name='Categoria Lexical'),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='classe_gramatical',
            field=models.CharField(default='substantivo', help_text='Ex: substantivo, verbo, adjetivo, advérbio.', max_length=100, verbose_name='Classe Gramatical'),
        ),
    ]
