# Generated by Django 6.1 on 2026-09-04 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0002_vocabularyitem_categoria_classe_gramatical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantetupi',
            name='codigo',
            field=models.SlugField(help_text='Ex: tupi, tupi_contemporaneo, tupinamba. Usado internamente e no RAG.', unique=True, verbose_name='Código Único'),
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('escolha_multipla', 'Múltipla Escolha'), ('completar', 'Completar Lacunas'), ('associacao', 'Associação de Pares'), ('audio', 'Reconhecimento de Áudio'), ('traducao', 'Tradução Livre')], help_text='escolha_multipla, completar ou associacao.', max_length=30, verbose_name='Tipo de Exercício')),
                ('enunciado', models.CharField(max_length=500, verbose_name='Enunciado')),
                ('explicacao', models.TextField(blank=True, help_text='Exibida após o usuário responder. Explica a resposta correta com contexto cultural.', verbose_name='Explicação')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='Dificuldade')),
                ('pontos_base', models.PositiveSmallIntegerField(default=10, verbose_name='Pontos Base (XP)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem na Lição')),
                ('midia', models.FileField(blank=True, help_text='Imagem ou áudio de apoio ao enunciado.', null=True, upload_to='exercicios/media/', verbose_name='Mídia de Apoio')),
                ('opcoes', models.JSONField(blank=True, help_text='Lista de strings. Ex: ["Kauê", "Pirá", "Tupã", "Taba"]', null=True, verbose_name='Opções de Múltipla Escolha')),
                ('resposta_correta', models.PositiveSmallIntegerField(blank=True, help_text='Índice 0-based da opção correta. Ex: 0 para a primeira.', null=True, verbose_name='Índice da Resposta Correta')),
                ('texto_com_lacunas', models.TextField(blank=True, help_text='Use ___ para marcar cada lacuna. Ex: \'Ao avistar um amigo: "___!"\'', null=True, verbose_name='Texto com Lacunas')),
                ('respostas_corretas', models.JSONField(blank=True, help_text='Lista de strings com respostas aceitas. Ex: ["Kauê"]', null=True, verbose_name='Respostas Corretas (Lacunas)')),
                ('tolerancia_levenshtein', models.PositiveSmallIntegerField(default=2, help_text='Distância máxima permitida para typos. 0=exato, 1=1 erro, 2=2 erros.', verbose_name='Tolerância a Erros (Levenshtein)')),
                ('coluna_esquerda', models.JSONField(blank=True, help_text='Lista de strings. Ex: ["Kauê", "Kunhã", "Taba"]', null=True, verbose_name='Coluna da Esquerda')),
                ('coluna_direita', models.JSONField(blank=True, help_text='Lista de strings. Ex: ["Aldeia", "Olá", "Mulher"]', null=True, verbose_name='Coluna da Direita')),
                ('associacao_correta', models.JSONField(blank=True, help_text='Dict índice->índice. Ex: {"0": "1", "1": "2", "2": "0"}', null=True, verbose_name='Associação Correta')),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='trilha.licao', verbose_name='Lição')),
                ('story_block', models.ForeignKey(blank=True, help_text='Se preenchido, este exercício aparece dentro daquele bloco específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercicios', to='trilha.storyblock', verbose_name='Bloco de História')),
            ],
            options={
                'verbose_name': 'Exercício Unificado',
                'verbose_name_plural': 'Exercícios Unificados',
                'db_table': 'trilha_exercicio',
                'ordering': ['licao', 'ordem'],
            },
        ),
    ]
