# Generated by Django 6.1 on 2026-09-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0003_alter_variantetupi_codigo_exercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='tolerancia_levenshtein',
            field=models.PositiveSmallIntegerField(blank=True, default=2, help_text='Distância máxima permitida para typos. 0=exato, 1=1 erro, 2=2 erros.', null=True, verbose_name='Tolerância a Erros (Levenshtein)'),
        ),
    ]
