# Generated by Django 6.1 on 2026-09-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0004_alter_exercicio_tolerancia_levenshtein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='publicado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='licao',
            name='publicada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicada'),
        ),
    ]
