# Generated by Django 6.1 on 2026-09-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0005_alter_capitulo_publicado_alter_licao_publicada'),
        ('users', '0005_userprofile_dias_estudados_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChestReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_index', models.IntegerField(default=1, verbose_name='Índice do Marco na Trilha')),
                ('recompensa_xp', models.IntegerField(default=75, verbose_name='XP da Recompensa')),
                ('recompensa_conchas', models.IntegerField(default=50, verbose_name='Conchas da Recompensa')),
                ('coletado_em', models.DateTimeField(auto_now_add=True, verbose_name='Coletado em')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chests_coletados', to='trilha.capitulo', verbose_name='Capítulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chests_coletados', to='users.userprofile', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Baú Coletado pelo Usuário',
                'verbose_name_plural': 'Baús Coletados pelos Usuários',
                'db_table': 'trilha_userchestreward',
                'indexes': [models.Index(fields=['user', 'capitulo'], name='idx_userchest_user_cap')],
                'unique_together': {('user', 'capitulo', 'milestone_index')},
            },
        ),
    ]
