# Generated by Django 6.1 on 2026-09-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0005_alter_capitulo_publicado_alter_licao_publicada'),
        ('users', '0003_achievement_filaexerciciousuario_userachievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='concluida_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Concluída em'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='status',
            field=models.CharField(choices=[('bloqueada', 'Bloqueada'), ('disponivel', 'Disponível'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], db_index=True, default='bloqueada', max_length=15, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='userlesson',
            index=models.Index(fields=['usuario', 'status'], name='users_userl_usuario_6d82e2_idx'),
        ),
        migrations.AddIndex(
            model_name='userlesson',
            index=models.Index(fields=['usuario', 'concluida_em'], name='users_userl_usuario_aead26_idx'),
        ),
    ]
