# Generated by Django 6.1 on 2026-09-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_userlesson_concluida_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dias_estudados_total",
            field=models.IntegerField(
                default=0,
                help_text="Contagem total de dias com pelo menos uma atividade concluída.",
                verbose_name="Dias Estudados no Total",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="maior_streak",
            field=models.IntegerField(
                default=0,
                help_text="Maior sequência de dias consecutivos já atingida.",
                verbose_name="Maior Ofensiva (Recorde)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streak_atual",
            field=models.IntegerField(
                default=0,
                help_text="Dias consecutivos de estudo ativo do usuário.",
                verbose_name="Ofensiva Atual (Dias)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ultimo_dia_estudado",
            field=models.DateField(
                blank=True,
                help_text="Data da última atividade válida no fuso America/Sao_Paulo.",
                null=True,
                verbose_name="Último Dia Estudado",
            ),
        ),
        migrations.CreateModel(
            name="DailyStudyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        help_text="Data no fuso horário America/Sao_Paulo",
                        verbose_name="Data da Atividade",
                    ),
                ),
                (
                    "xp_ganho",
                    models.IntegerField(default=0, verbose_name="XP Ganho no Dia"),
                ),
                (
                    "licoes_concluidas",
                    models.IntegerField(default=0, verbose_name="Lições Concluídas"),
                ),
                (
                    "exercicios_respondidos",
                    models.IntegerField(
                        default=0, verbose_name="Exercícios Respondidos"
                    ),
                ),
                (
                    "exercicios_corretos",
                    models.IntegerField(default=0, verbose_name="Exercícios Corretos"),
                ),
                (
                    "tempo_estudo_segundos",
                    models.IntegerField(
                        default=0, verbose_name="Tempo de Estudo (Segundos)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_study_logs",
                        to="users.userprofile",
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Diário de Estudo",
                "verbose_name_plural": "Logs Diários de Estudo",
                "db_table": "users_daily_study_log",
                "indexes": [
                    models.Index(
                        fields=["user", "-data"], name="idx_dailylog_user_data_desc"
                    )
                ],
                "unique_together": {("user", "data")},
            },
        ),
    ]
