# Generated by Django 6.1 on 2026-09-11 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0006_userchestreward'),
        ('users', '0005_userprofile_dias_estudados_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='conchas',
            field=models.IntegerField(default=0, help_text='Moeda do Pindorama acumulada em lições e práticas.', verbose_name='Conchas (Moeda)'),
        ),
        migrations.CreateModel(
            name='HistoricoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_tupi', models.CharField(max_length=200, verbose_name='Palavra em Tupi')),
                ('traducao_pt', models.CharField(blank=True, default='', max_length=200, verbose_name='Tradução em Português')),
                ('status', models.CharField(max_length=20, verbose_name='Status de Validação')),
                ('similaridade', models.FloatField(default=0.0, verbose_name='Similaridade Trigramas')),
                ('time_taken_seconds', models.FloatField(default=0.0, verbose_name='Tempo de Resposta (s)')),
                ('origem', models.CharField(default='pratica_tematica', max_length=50, verbose_name='Origem do Exercício')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_respostas', to='users.userprofile', verbose_name='Usuário')),
                ('vocabulary_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_respostas', to='trilha.vocabularyitem', verbose_name='Item de Vocabulário')),
            ],
            options={
                'verbose_name': 'Histórico de Resposta',
                'verbose_name_plural': 'Histórico de Respostas',
                'db_table': 'users_historicoresposta',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_histresp_user_status'), models.Index(fields=['palavra_tupi'], name='idx_histresp_palavra'), models.Index(fields=['-created_at'], name='idx_histresp_created_at')],
            },
        ),
    ]
