# Generated by Antigravity on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_conchas_historicoresposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=64, verbose_name='ID do Item')),
                ('item_type', models.CharField(max_length=32, verbose_name='Tipo (theme, avatar, frame, special_lesson)')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Desbloqueado em')),
                ('is_equipped', models.BooleanField(default=False, verbose_name='Equipado Atualmente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmeticos', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Cosmético do Usuário',
                'verbose_name_plural': 'Cosméticos dos Usuários',
                'db_table': 'users_cosmetics',
            },
        ),
        migrations.CreateModel(
            name='CosmeticPurchaseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64, verbose_name='ID do Item')),
                ('item_price', models.IntegerField(verbose_name='Preço em Conchas')),
                ('balance_before', models.IntegerField(verbose_name='Saldo Anterior')),
                ('balance_after', models.IntegerField(verbose_name='Saldo Posterior')),
                ('hmac_receipt', models.CharField(max_length=128, verbose_name='Assinatura HMAC-SHA256 do Servidor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Compra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_loja', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Auditoria de Compra de Cosmético',
                'verbose_name_plural': 'Auditorias de Compras de Cosméticos',
                'db_table': 'users_cosmetic_purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usercosmetic',
            index=models.Index(fields=['user', 'item_type', 'is_equipped'], name='users_cosme_user_id_4e5904_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercosmetic',
            unique_together={('user', 'item_id')},
        ),
    ]
